---
- name: Creating an EC2 Security Group inside the Mentioned VPC
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ vpc_region }}"
    state: present
    rules: "{{ item.rules }}"
  with_items: "{{ ec2_security_groups }}"
  register: aws_sg

- name: Tag the Security Groups with Distinguished Name
  ec2_tag:
    resource: "{{ item.group_id }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ item.item.name }}"
      Environment: "{{ Environment }}"
  with_items: "{{ aws_sg.results }}"

- name: Set fact for SG
  set_fact:
    ec2_security_group: "{{ item.item.name }}"
  with_items: "{{ aws_sg.results }}"