---
# Variables that can provide as extra vars
VPC_REGION: us-east-1 # N.Virginia
EC2_INSTANCE_TYPE: t2.medium
EC2_KEY_NAME: "rubykey"
EC2_SECURITY_GROUP_NAME: "RubySecurityGroup"
EC2_COUNT: 1
EC2_VOLUME_SIZE: 20
EC2_SUBNET_ID: subnet-09554527
EC2_USER: "ec2-user"
# Example of EC2_SUBNET_ID
# EC2_SUBNET_ID:
#   - "subnet-0c3e0b7b"
#   - "subnet-bf672ae6"
AMI_NAME: "ami-0323c3dd2da7fb37d"

# Use inside the tasks
vpc_region: "{{ VPC_REGION }}"
ec2_instance_type: "{{ EC2_INSTANCE_TYPE }}"
ec2_key_name: "{{ EC2_KEY_NAME }}"
ec2_security_group_name: "{{ EC2_SECURITY_GROUP_NAME }}"
ec2_volume_size: "{{ EC2_VOLUME_SIZE }}"
ec2_count: "{{ EC2_COUNT }}"
ec2_subnet_id: "{{ EC2_SUBNET_ID }}"
ec2_user: "{{ EC2_USER }}"
ami_name: "{{ AMI_NAME }}"

# Tags
ENVIRONMENT: Dev
SERVERNAME: RubyWebServer